// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProLab.Areas.ProGym.Data;

#nullable disable

namespace ProLab.Migrations.ProGym
{
    [DbContext(typeof(ProGymContext))]
    [Migration("20260126210140_ProGymExercisesAdded")]
    partial class ProGymExercisesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProLab.Areas.ProGym.Models.DataModels.ProGymExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ProGymAxerciseImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ProGymExerciseDescription")
                        .HasColumnType("text");

                    b.Property<string>("ProGymExerciseName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProGymExercises");
                });

            modelBuilder.Entity("ProLab.Areas.ProGym.Models.DataModels.ProGymWorkOut", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ProGymWorkOuts");
                });

            modelBuilder.Entity("ProLab.Areas.ProGym.Models.DataModels.ProGymWorkoutExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProGymExerciseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProGymWorkOutId")
                        .HasColumnType("integer");

                    b.Property<int>("Reps")
                        .HasColumnType("integer");

                    b.Property<int>("Sets")
                        .HasColumnType("integer");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ProGymExerciseId");

                    b.HasIndex("ProGymWorkOutId");

                    b.ToTable("ProGymWorkoutExercises");
                });

            modelBuilder.Entity("ProLab.Areas.ProGym.Models.DataModels.ProGymWorkoutExercise", b =>
                {
                    b.HasOne("ProLab.Areas.ProGym.Models.DataModels.ProGymExercise", "ProGymExercise")
                        .WithMany()
                        .HasForeignKey("ProGymExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProLab.Areas.ProGym.Models.DataModels.ProGymWorkOut", "ProGymWorkOut")
                        .WithMany()
                        .HasForeignKey("ProGymWorkOutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProGymExercise");

                    b.Navigation("ProGymWorkOut");
                });
#pragma warning restore 612, 618
        }
    }
}
