// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProLab.Areas.HockeyData.Data;

#nullable disable

namespace ProLab.Migrations.HockeyData
{
    [DbContext(typeof(HockeyDataContext))]
    [Migration("20260121183153_HockeyGamesAdded")]
    partial class HockeyGamesAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyArena", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("HockeyArenaName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HockeyArenas");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AwayTeamScore")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("GameDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GameNumber")
                        .HasColumnType("text");

                    b.Property<int?>("HockeyArenaId")
                        .HasColumnType("integer");

                    b.Property<int?>("HockeyGameStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("HockeySeriesId")
                        .HasColumnType("integer");

                    b.Property<int?>("HockeyTeamId")
                        .HasColumnType("integer");

                    b.Property<int?>("HockeyTeamId1")
                        .HasColumnType("integer");

                    b.Property<int?>("HomeTeamScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HockeyArenaId");

                    b.HasIndex("HockeyGameStatusId");

                    b.HasIndex("HockeySeriesId");

                    b.HasIndex("HockeyTeamId");

                    b.HasIndex("HockeyTeamId1");

                    b.ToTable("HockeyGames");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyGameStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HockeyGameStatusName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HockeyGameStatuses");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Age")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("SSN")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HockeyPlayers");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyPlayersHockeyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HockeyPlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("HockeyTeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HockeyPlayerId");

                    b.HasIndex("HockeyTeamId");

                    b.ToTable("HockeyPlayersHockeyTeam");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeySeries", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameTime")
                        .HasColumnType("text");

                    b.Property<string>("HockeySeriesDescription")
                        .HasColumnType("text");

                    b.Property<string>("HockeySeriesName")
                        .HasColumnType("text");

                    b.Property<string>("HockeySeriesShortDescription")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HockeySeries");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachName")
                        .HasColumnType("text");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<int?>("HockeyArenaId")
                        .HasColumnType("integer");

                    b.Property<string>("HockeyTeamBadgePath")
                        .HasColumnType("text");

                    b.Property<string>("HockeyTeamName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HockeyArenaId");

                    b.ToTable("HockeyTeams");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyGame", b =>
                {
                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyArena", "HockeyArena")
                        .WithMany()
                        .HasForeignKey("HockeyArenaId");

                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyGameStatus", "GameStatus")
                        .WithMany()
                        .HasForeignKey("HockeyGameStatusId");

                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeySeries", "HockeySeries")
                        .WithMany()
                        .HasForeignKey("HockeySeriesId");

                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HockeyTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("HockeyTeamId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AwayTeam");

                    b.Navigation("GameStatus");

                    b.Navigation("HockeyArena");

                    b.Navigation("HockeySeries");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyPlayersHockeyTeam", b =>
                {
                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyPlayer", "HockeyPlayer")
                        .WithMany()
                        .HasForeignKey("HockeyPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", "HockeyTeam")
                        .WithMany("HockeyPlayers")
                        .HasForeignKey("HockeyTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HockeyPlayer");

                    b.Navigation("HockeyTeam");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", b =>
                {
                    b.HasOne("ProLab.Areas.HockeyData.Models.DataModels.HockeyArena", "HomeArena")
                        .WithMany()
                        .HasForeignKey("HockeyArenaId");

                    b.Navigation("HomeArena");
                });

            modelBuilder.Entity("ProLab.Areas.HockeyData.Models.DataModels.HockeyTeam", b =>
                {
                    b.Navigation("HockeyPlayers");
                });
#pragma warning restore 612, 618
        }
    }
}
